cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}
    --output=logs/{rule}/%j.out
    --error=logs/{rule}/%j.err
    --time={resources.time}
default-resources:
  - partition=tier1q
  - mem_mb=1000
  - time="01:00:00"
restart-times: 10
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 300
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy